name = "Create - Friends and Family"
author = "CyanCupcake"
version = "0.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7a05d4d272f374d6174493b8390d198f3428a1e912e5ac6b1643a7aa54dee1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
