name = "Create - Friends and Family"
author = "CyanCupcake"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ea1999c2932af60d9d8a26a45eba387b18b730516c5bd3395b9234f8b644f66"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"

[update]
url = "https://cyan-cupcake.github.io/create-friends-family/pack.toml"
