name = "Create - Friends and Family"
author = "CyanCupcake"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b0c6a6218a4d8b7157b4a3c2051424265205ad35c58f025933598f10a5bf158"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
