# Don't change this! Version used to track needed updates.
version = 0
language = "en"
populationMultiplier = 5
buildingMultiplier = 10
averageBuildingLevelMultiplier = 100
claimedChunksMultiplier = 10
overallHappinessMultiplier = 5